
name: Deploy Netlify site
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
      
    - name: Install dependencies, build and test
      run: |
        npm install
        npm run build
        npm test
        
#     - name: Deploy to Production
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         personal_token: ${{ secrets.PERSONAL_TOKEN }}
#         publish_branch: gh-pages
#         publish_dir: ./build

    - name: Trigger Netlify Build Hook
      if: success()
      env:
        BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK }}
      run: |
        curl -X POST -d {} "${BUILD_HOOK_URL}"
