
name: Deploy Netlify site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      # run 
      - name: Deploy site
        run: curl -X POST -d {} ${{ sEcrets.NETLIFY_BUILD_HOOK }}
